# This is a sample build configuration for C++ ï¿½ Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: pjknowles/opensuse:2018-11-06

pipelines:
  default:
    - step:
        caches:
          - cmake
#          - dependencies
        script: # Modify the commands below to build your repository.
#          -  zypper -n install eigen3-devel cmake gcc-fortran gcc-c++ openmpi-devel openmpi-libs blas-devel libblas3 git doxygen texlive-epstopdf ghostscript lapack
#          - ln -s /usr /usr/usr
          - TOP=$PWD; BUILD=build/$(git rev-parse --abbrev-ref HEAD) ; mkdir -p $BUILD && cd $BUILD && pwd && cmake $TOP
          - cmake --build . -- -j 16
          - cd test && ctest -V
definitions:
  caches:
    cmake: build
    dependencies: build
options:
  max-time: 5